### ISSUE TITLE
Убрать баг во вкладке quests связанный с инерфейсом контролла "Найти".

### ISSUE THREAD

**Issue by MozalovPavel** [urfu-2016/team5#147]
Если открыть вкладку параметры и уменьшать экран, то в определенный момент контролл "Искать только в поле" уедет вниз под карточки.

**Comment by AlSoEdit** [comment]
@MozalovPavel Кажется, уже не актуально, либо я не смог воспроизвести. Если уже починили, тогда закрывай.

**Comment by MozalovPavel** [comment]
@AlSoEdit баг все еще остался.
