### ISSUE TITLE
Username в базе в lowercase

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#181]
Нужно не забыть про обработку этого, дописать что-то

**Comment by AlSoEdit** [comment]
@dimastark Что делать с этим? В базе сохраняется в lower. Если вдруг кто-то захочет, допустим, авторизоваться с ником не в lower, тогда такой пользователь не будет найден. Такое место не одно, мне кажется, так что нужно какое-то общее решение.

**Comment by dimastark** [comment]
Пофиксил в узких местах
