### ISSUE TITLE
Использовать update в моделях

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#182]
Вместо 
`
const instance = Model.findOne(...);
instance.someField = newValue;
instance.save();
`

Использовать update. Тогда значение будет обновлено за запрос в базу.
http://mongoosejs.com/docs/api.html#model_Model.update

**Comment by dimastark** [comment]
Посмотрел. В моделях нельзя этого сделать, так как везде нужно возвращать измененный объект. А model.update ничего не возвращает

**Comment by AlSoEdit** [comment]
@dimastark https://mongodb.github.io/node-mongodb-native/2.2/api/Collection.html#findOneAndUpdate
