### ISSUE TITLE
Добавить модель User, по формату в вики

### ISSUE THREAD

**Issue by dimastark** [urfu-2016/team5#36]
[Формат](https://github.com/urfu-2016/team5/wiki/%D0%91%D0%B0%D0%B7%D0%B0-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85#user)

**Comment by dimastark** [comment]
Плюс добавить тесты по спецификации

**Comment by AlSoEdit** [comment]
#38
