### ISSUE TITLE
Логика для поиска квестов

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#56]

**Comment by dimastark** [comment]
Сюда напиши, как что-то придумаешь

**Comment by MozalovPavel** [comment]
Сначала сделаю поиск только по внутренним свойствам. Т.е. title и tags. После того как добьем генерацию можно будет реализовать поиск по автору и добавить фильтрацию по лайкам.

**Comment by dimastark** [comment]
Ок, раз я делаю генерацию, подумаю над указанием автора в квесте
