### ISSUE TITLE
Клиентская логика для авторизации

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#57]

**Comment by dimastark** [comment]
Давай тогда сначала сюда напишешь, как придумаешь что-то

**Comment by AlSoEdit** [comment]
Скрыть кнопки авторизации и регистрации, добавить кнопку logout

**Comment by dimastark** [comment]
Нужно поправить текущие формы. Сейчас после логина приходит json. Надо вместо формы сделать fetch, либо еще как-то, чтобы потом полученные данные отрисовать

**Comment by AlSoEdit** [comment]
@dimastark актуально? Кажется, это issue про валидацию в формах, да?
