### ISSUE TITLE
Настроить webpack.

### ISSUE THREAD

**Issue by MozalovPavel** [urfu-2016/team5#72]
Чтобы хорошо собирал все css и клиентский js в бандлы для css и js.
+ настройка препроцессинга, постпроцессинга и др. штук.
+ не забудь про минификацию)

**Comment by AlSoEdit** [comment]
У нас используется пре-постпроцессинг?

**Comment by dimastark** [comment]
Нет

**Comment by dimastark** [comment]
Леша, надо подумать, что из фич вебпака нам нужно. Думаю эта задача лучше на тебя
