### ISSUE TITLE
Переписать generate-db-data и тесты с учетом account

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#79]

**Comment by dimastark** [comment]
А что имеется в виду?

**Comment by AlSoEdit** [comment]
@dimastark Паша переписал генерацию квестов через генерацию пользователей, которые генерируют квесты. Думаю, нужно еще добавить генерацию аккаунтов + написать тесты на это. Паша переписал скрипт, но тесты не переписал.
