### ISSUE TITLE
Написать документацию

### ISSUE THREAD

**Issue by AlSoEdit** [urfu-2016/team5#90]

**Comment by dimastark** [comment]
Нужно описать все штуки из бека, которые мы написали

**Comment by AlSoEdit** [comment]
@dimastark я так понимаю нужно добавить комментарии в код

**Comment by dimastark** [comment]
@AlSoEdit Заполнить вики на github и добавить доку к функциям, например

**Comment by dimastark** [comment]
Явных комментов не нужно
